name: '🐛 Bug report'
description: Create a report to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the bug template! 🙏

  - type: checkboxes
    id: latest-version-swoosh
    attributes:
      label: Have you tried the latest version of Swoosh?
      description: You may want to try the latest version first ;)
      options:
        - label: 'Yes'

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: Describe the steps we have to take to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.

  - type: input
    id: link
    attributes:
      label: Your reproducible example
      placeholder: |
        e.g. https://github.com/your/repo

  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓

  - type: textarea
    id: platform
    attributes:
      label: Platform
      value: |
        - OTP:
        - Elixir:

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
